# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_cppDataFrameInterface <- function(x, y, catCols, linCols, numRows, numColumns, featureWeights, featureWeightsVariables, deepFeatureWeights, deepFeatureWeightsVariables, observationWeights, monotonicConstraints) {
    .Call(`_Rforestry_rcpp_cppDataFrameInterface`, x, y, catCols, linCols, numRows, numColumns, featureWeights, featureWeightsVariables, deepFeatureWeights, deepFeatureWeightsVariables, observationWeights, monotonicConstraints)
}

rcpp_cppBuildInterface <- function(x, y, catCols, linCols, numRows, numColumns, ntree, replace, sampsize, mtry, splitratio, nodesizeSpl, nodesizeAvg, nodesizeStrictSpl, nodesizeStrictAvg, minSplitGain, maxDepth, interactionDepth, seed, nthread, verbose, middleSplit, maxObs, featureWeights, featureWeightsVariables, deepFeatureWeights, deepFeatureWeightsVariables, observationWeights, monotonicConstraints, hasNas, linear, overfitPenalty, doubleTree, existing_dataframe_flag, existing_dataframe) {
    .Call(`_Rforestry_rcpp_cppBuildInterface`, x, y, catCols, linCols, numRows, numColumns, ntree, replace, sampsize, mtry, splitratio, nodesizeSpl, nodesizeAvg, nodesizeStrictSpl, nodesizeStrictAvg, minSplitGain, maxDepth, interactionDepth, seed, nthread, verbose, middleSplit, maxObs, featureWeights, featureWeightsVariables, deepFeatureWeights, deepFeatureWeightsVariables, observationWeights, monotonicConstraints, hasNas, linear, overfitPenalty, doubleTree, existing_dataframe_flag, existing_dataframe)
}

rcpp_cppMultilayerBuildInterface <- function(x, y, catCols, linCols, numRows, numColumns, ntree, nrounds, eta, replace, sampsize, mtry, splitratio, nodesizeSpl, nodesizeAvg, nodesizeStrictSpl, nodesizeStrictAvg, minSplitGain, maxDepth, seed, nthread, verbose, middleSplit, maxObs, featureWeights, featureWeightsVariables, deepFeatureWeights, deepFeatureWeightsVariables, observationWeights, monotonicConstraints, linear, overfitPenalty, doubleTree, existing_dataframe_flag, existing_dataframe) {
    .Call(`_Rforestry_rcpp_cppMultilayerBuildInterface`, x, y, catCols, linCols, numRows, numColumns, ntree, nrounds, eta, replace, sampsize, mtry, splitratio, nodesizeSpl, nodesizeAvg, nodesizeStrictSpl, nodesizeStrictAvg, minSplitGain, maxDepth, seed, nthread, verbose, middleSplit, maxObs, featureWeights, featureWeightsVariables, deepFeatureWeights, deepFeatureWeightsVariables, observationWeights, monotonicConstraints, linear, overfitPenalty, doubleTree, existing_dataframe_flag, existing_dataframe)
}

rcpp_cppPredictInterface <- function(forest, x, aggregation, seed) {
    .Call(`_Rforestry_rcpp_cppPredictInterface`, forest, x, aggregation, seed)
}

rcpp_cppMultilayerPredictInterface <- function(multilayerForest, x, aggregation, seed) {
    .Call(`_Rforestry_rcpp_cppMultilayerPredictInterface`, multilayerForest, x, aggregation, seed)
}

rcpp_OBBPredictInterface <- function(forest) {
    .Call(`_Rforestry_rcpp_OBBPredictInterface`, forest)
}

rcpp_OBBPredictionsInterface <- function(forest) {
    .Call(`_Rforestry_rcpp_OBBPredictionsInterface`, forest)
}

rcpp_VariableImportanceInterface <- function(forest) {
    .Call(`_Rforestry_rcpp_VariableImportanceInterface`, forest)
}

rcpp_getObservationSizeInterface <- function(df) {
    .Call(`_Rforestry_rcpp_getObservationSizeInterface`, df)
}

rcpp_AddTreeInterface <- function(forest, ntree) {
    invisible(.Call(`_Rforestry_rcpp_AddTreeInterface`, forest, ntree))
}

rcpp_CppToR_translator <- function(forest) {
    .Call(`_Rforestry_rcpp_CppToR_translator`, forest)
}

rcpp_gammas_translator <- function(multilayerForest) {
    .Call(`_Rforestry_rcpp_gammas_translator`, multilayerForest)
}

rcpp_residuals_translator <- function(multilayerForest) {
    .Call(`_Rforestry_rcpp_residuals_translator`, multilayerForest)
}

rcpp_multilayer_CppToR_translator <- function(multilayerForest) {
    .Call(`_Rforestry_rcpp_multilayer_CppToR_translator`, multilayerForest)
}

rcpp_reconstructree <- function(x, y, catCols, linCols, numRows, numColumns, R_forest, replace, sampsize, splitratio, mtry, nodesizeSpl, nodesizeAvg, nodesizeStrictSpl, nodesizeStrictAvg, minSplitGain, maxDepth, interactionDepth, seed, nthread, verbose, middleSplit, maxObs, featureWeights, featureWeightsVariables, deepFeatureWeights, deepFeatureWeightsVariables, observationWeights, monotonicConstraints, hasNas, linear, overfitPenalty, doubleTree) {
    .Call(`_Rforestry_rcpp_reconstructree`, x, y, catCols, linCols, numRows, numColumns, R_forest, replace, sampsize, splitratio, mtry, nodesizeSpl, nodesizeAvg, nodesizeStrictSpl, nodesizeStrictAvg, minSplitGain, maxDepth, interactionDepth, seed, nthread, verbose, middleSplit, maxObs, featureWeights, featureWeightsVariables, deepFeatureWeights, deepFeatureWeightsVariables, observationWeights, monotonicConstraints, hasNas, linear, overfitPenalty, doubleTree)
}

rcpp_reconstruct_forests <- function(x, y, catCols, linCols, numRows, numColumns, R_forests, R_residuals, nrounds, eta, replace, sampsize, splitratio, mtry, nodesizeSpl, nodesizeAvg, nodesizeStrictSpl, nodesizeStrictAvg, minSplitGain, maxDepth, seed, nthread, verbose, middleSplit, maxObs, featureWeights, featureWeightsVariables, deepFeatureWeights, deepFeatureWeightsVariables, observationWeights, monotonicConstraints, gammas, linear, overfitPenalty, doubleTree) {
    .Call(`_Rforestry_rcpp_reconstruct_forests`, x, y, catCols, linCols, numRows, numColumns, R_forests, R_residuals, nrounds, eta, replace, sampsize, splitratio, mtry, nodesizeSpl, nodesizeAvg, nodesizeStrictSpl, nodesizeStrictAvg, minSplitGain, maxDepth, seed, nthread, verbose, middleSplit, maxObs, featureWeights, featureWeightsVariables, deepFeatureWeights, deepFeatureWeightsVariables, observationWeights, monotonicConstraints, gammas, linear, overfitPenalty, doubleTree)
}

rcpp_cppImputeInterface <- function(forest, x, seed) {
    .Call(`_Rforestry_rcpp_cppImputeInterface`, forest, x, seed)
}

